name: Weekly Player List Scraper

on:
  workflow_dispatch: # Only manual/API triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install tzdata
        pip install playwright
        playwright install chromium
        playwright install-deps
    
    - name: Run scraper
      env:
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: |
        python Webscrape.py